Remove __cxa_thread_atexit stubs (#15531)
Back in #14489 we started using the implemenation of
`__cxa_thread_atexit` from libcxxabi so this is stub should never be
needed.

This change also involves renaming the test from `.c` to `.cpp` since
C programs don't generally have access to `__cxa_thread_atexit` (its
part of libcxxabi).

I also removed the call to `__cxa_thread_atexit_impl` since we don't
define that anywhere in emscripten.

Also run this tests with threads enabled which would have resulted
in an undefined reference to `__cxa_thread_atexit_impl` previously.